spring.application.name=lesson

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_LESSON_DB}
spring.datasource.username=${POSTGRES_LESSON_USER}
spring.datasource.password=${POSTGRES_LESSON_PASSWORD}

spring.flyway.locations=classpath:bd/migrations

